name: Cron BCK every weekend

on:
  schedule:
    - cron: "0 0 * * 6,0"
#on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Installing PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: '7.3'
    - name: Installing Terminus
      uses: kopepasah/setup-pantheon-terminus@master
      with:
        pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
    - name: update files
      if: success()
      run: terminus import:files ${{ secrets.PANTHEON_DOMAIN }} https://github.com/${{GITHUB_REPOSITORY_OWNER}}/${{GITHUB_REPOSITORY}}/raw/master/killme.zip --yes

    - name: commit the changed
      if: success()
      run: terminus env:commit --message "updated" --force -- ${{ secrets.PANTHEON_DOMAIN }}
